### ISSUE TITLE
[Bug] Balance gone after upgrading to 1.3.1

### ISSUE THREAD

**Issue by mmitech** [Chia-Network/chia-blockchain#10803]
### What happened?

After upgrading to the latest version (1.3.1) it seems like my wallet balance is gone, downgrading back seems to solve the issue, I have only one wallet mnemonic (key) and I am farming using NFT plots, did both pool and self pooling.

I am just speculating here since downgrading seems to solve the issue but chia's BLS is based on BIP32 so when upgrading my wallet it should always scan addresses derived (including change addresses) from my own mnemonic... so why it doesn't scan for my balance correctly 

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
after you upgrade to 1.3.x delete the wallet db, and let it resync, all your coins will come back
https://www.chia.net/2022/01/10/understanding-the-changes-in-the-new-light-wallet.en.html

**Comment by mmitech** [comment]
tried that as well, didn't really help

**Comment by youngfong13** [comment]
I upgrade to 1.3.1 and now my wallet balance is wrong on my linux machine. It isn't zero, but isn't showing any transactions after 2-21-2022. I get a daily farming pool payout and on a lite wallet on another machine running 1.3.1 it is showing a higher (and I believe correct) balance. Running 1.3.1 on Ubuntu (where the balance is wrong) and 1.3.1 on MacOS intel (lite wallet).

**Comment by youngfong13** [comment]
> I upgrade to 1.3.1 and now my wallet balance is wrong on my linux machine. It isn't zero, but isn't showing any transactions after 2-21-2022. I get a daily farming pool payout and on a lite wallet on another machine running 1.3.1 it is showing a higher (and I believe correct) balance. Running 1.3.1 on Ubuntu (where the balance is wrong) and 1.3.1 on MacOS intel (lite wallet).

I deleted all the files in .chia/mainnet/wallet/db and now the balance is correct on the linux machine.

**Comment by mmitech** [comment]
I sent all the funds from 1.2.11 to a new address generated on a different machine that has 1.3.1, this is how I "resolved" the issue

**Comment by mmitech** [comment]
The issue persists, now after I reinstalled and resynced the wallet, the whole balance is gone and the command chia keys derive search "ADDRESS" returns "Could not find 'xch..'"

I am unable to retrieve my XCH for the life of me, downgrading doesn't help since the new old way key derivation (path?) doesn't seem to be compatible with the newly generated address.

**Comment by mmitech** [comment]
The issue still persists

**Comment by emlowe** [comment]
Possibly fixed in https://github.com/Chia-Network/chia-blockchain/pull/11338

**Comment by mmitech** [comment]
Issue still not fixed https://github.com/Chia-Network/chia-blockchain/issues/11194#issuecomment-1114478474

**Comment by yalin161815** [comment]
chia 1.26升级1.32 钱包的余额变成0，下面有转账记录，接收地址竟然是自己的之前的接收地址，现在怎么办

**Comment by emlowe** [comment]
Please test with 1.3.5 as various fixes for this are in 1.3.5. Closing issue. Feel free to re-open if problems continue with 1.3.5

**Comment by xlgosx** [comment]
> after you upgrade to 1.3.x delete the wallet db, and let it resync, all your coins will come back https://www.chia.net/2022/01/10/understanding-the-changes-in-the-new-light-wallet.en.html

It worked great, you will find wallet db in windows installation drive, 1st close the the chia app if its running, then open local disk, then open users, it should be under the main user(changes by computer), then click the .chia folder,  then click mainnet, then open wallet folder, open db folder, once inside db folder, just delete the files that say blockhain_wallet and not the wallet_peers. close the window then open chia program once again and the wallet or token tab should reflect the correct chia amount.
