### ISSUE TITLE
[BUG] 1.0rc7 not syncing on Ubuntu 18.04.5

### ISSUE THREAD

**Issue by robwedd** [Chia-Network/chia-blockchain#1313]
Upgraded to 1.0rc7 and the node will not sync. It connects and finds the number of blocks but the "Blocks" section of the GUI is stuck loading. I have deleted and re-installed three times with the same result.
![Screenshot from 2021-03-16 10-17-47](https://user-images.githubusercontent.com/58349420/111234041-d9341f00-8641-11eb-9cbb-0e7f92ffd248.png)

Running on Ubuntu 18.04.5 LTS
Intel Core-i5-4300U

**Comment by dorkmo** [comment]
are you connected to any peers in the connections section?

**Comment by robwedd** [comment]
Yes
![Screenshot from 2021-03-16 12-04-14](https://user-images.githubusercontent.com/58349420/111240702-cde7f000-864f-11eb-98ea-9dc45b192c0a.png)

**Comment by dorkmo** [comment]
looks like RC8 is about to come out tonight, might wait and see if that helps

**Comment by robwedd** [comment]
OK cheers, will do

**Comment by lvcivs** [comment]
How long did you wait? It happened to me a couple of times that it appeared like it were stuck for quite a while, but actually it was syncing and eventually got done.

**Comment by robwedd** [comment]
Thanks. I waited >12 hours before trying to reinstall each time. It been going for 24 hours now, still on "syncing 0/21390". Once my current plot is complete I'll update to RC8

**Comment by mariano54** [comment]
Fixed in rc9.

**Comment by robwedd** [comment]
Upgrade to rc9, testnet9. Still not syncing. When installing I get these warnings that might be relevant:

```
npm WARN @use-it/event-listener@0.1.6 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-scroll-to-bottom@4.1.1-master.2780945 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-simple-code-editor@0.10.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-simple-code-editor@0.10.0 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-teleporter@2.1.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-teleporter@2.1.1 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@5.1.1 requires a peer of webpack@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN use-dark-mode@2.3.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by robwedd** [comment]
re-installed and it now syncs
