### ISSUE TITLE
Self-pooling claims don't appear in the standard wallet transaction list (GUI & CLI)

### ISSUE THREAD

**Issue by shaneo257** [Chia-Network/chia-blockchain#13251]
### What happened?

User is currently farming solo, and when they claim the 1.75 reward from the block win, it doesn't show in the transaction list, but the XCH balance increases by the amount.  The transactions show in spacescan.

User has done a full wallet db resync and the transactions show, but the next block transactions wont show

I have a copy of the users logs if required

### Version

1.5.1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
can also confirm on 1.5.1 on ubuntu running on testnet
claimed the self pool rewards in the pooling tab, but no tx history in my Tokens tab

**Comment by jacoblroberts** [comment]
I think I'm experiencing the same.  I haven't tried re-syncing the db but from the original post stating a new claim reward will not show up even after re-syncing, I'll hold off on that.  Won 4 times since leaving a pool and only the farmer reward shows.  Version 1.6.1

**Comment by fnoquiq** [comment]
Same on here, I claim the 1.75 XCH and they disappeared from my wallet and my pool wallet. What should I do to find them?

**Comment by shaneo257** [comment]
its a known issue where the wallet tx history doesn't show the pool rewards, but your balance still increases just fine
it should be resolved in a future update

**Comment by fnoquiq** [comment]
@shaneo257 thank you very much for the reply! 😄

**Comment by iced-caffeine** [comment]
Just wanted to comment that this is still happening to me as of 1.6.1.

I'm not worried about it; the balance increases normally, and deleting the wallet.db/restarting will show the tx's.  However, they still don't show up in real-time when claimed on the Tokens -> Transactions pane.

**Comment by xklech** [comment]
Farmed block on 1.7.1 and did not receive 1.75 after the claim. Updated to 1.8.0 nothing changed.

Only after deleting wallet/db/*sqlite 1.75 appear. It scared the hell out of me and I spent 2 hours googling and checking addresses. The concept is confusing and with this bug really frustrating.

**Comment by HipLp** [comment]
Hello! The same thing happens to me, it's a shame that I just realized, in the last 4 blocks that I won, I received the reward of 1.75 from each of the blocks won, and I just realized that they did not reach my wallet or increase in the check. Any advice?

**Comment by cortseverns** [comment]
still a bug in 2.1.1 as of today (on Windows)

**Comment by emlowe** [comment]
This is fixed in #18887
