### ISSUE TITLE
[Bug] Non-existent connections not being removed from full node connections list

### ISSUE THREAD

**Issue by hwfanatic** [Chia-Network/chia-blockchain#15049]
### What happened?

I have 10 out of 60 incoming connections in full node connections list that no longer exist in the system as shown by TCPView. These connections are towards the top of the list and they are at least a couple of days old. Thy are not getting automatically removed from the list. They are not being mentioned in the debug log.

Usually I am able to remove them manually, which is getting tedious.

Sometimes however the removal fails and after 600 seconds the GUI becomes bugged - status becomes "Error" and other things are not being displayed properly or updated anymore. The GUI is unusable in this state and has to be restarted, but under the hood the farmer seems to keep submitting partials to the pool. No entries get created in the debug log.

![Screenshot 2023-04-17 090514](https://user-images.githubusercontent.com/18661613/232418558-315a21a8-cf07-440e-a4c3-55c593f3aa65.png)
![Screenshot 2023-04-17 090759](https://user-images.githubusercontent.com/18661613/232418572-12f5a019-0b9e-4445-8aaa-d78fc0aa6035.png)
![Screenshot 2023-04-17 091039](https://user-images.githubusercontent.com/18661613/232418575-e325e4fb-bc67-4c90-acdd-20f8ea681aab.png)
![Screenshot 2023-04-17 091206](https://user-images.githubusercontent.com/18661613/232418577-b6c8f4f5-f3da-4b1f-a511-9c0c99b18275.png)
![Screenshot 2023-04-17 091708](https://user-images.githubusercontent.com/18661613/232418581-f330484b-e29c-4df8-8060-615b83ba0ddf.png)
![Screenshot 2023-04-17 091826](https://user-images.githubusercontent.com/18661613/232418583-e7a4e232-4c5f-4ba1-9064-8bcd659c561a.png)
![Screenshot 2023-04-17 092003](https://user-images.githubusercontent.com/18661613/232418586-6d0a52f3-081b-42b7-9c89-b078ef64e317.png)
![Screenshot 2023-04-17 092057](https://user-images.githubusercontent.com/18661613/232418587-86ec8e40-0efd-4258-b8de-b1fe34699c3d.png)
![Screenshot 2023-04-17 092141](https://user-images.githubusercontent.com/18661613/232418589-98d7f686-5d45-4e0f-8ae7-5dfb8f9f7286.png)
![Screenshot 2023-04-17 092237](https://user-images.githubusercontent.com/18661613/232418591-83783152-ffb8-4d78-a87e-4b86de202f9b.png)
![Screenshot 2023-04-18 210106](https://user-images.githubusercontent.com/18661613/232879754-13090472-1ff8-4910-b5b4-c359baf8b808.png)
![Screenshot 2023-04-17 134323](https://user-images.githubusercontent.com/18661613/232474932-b225439d-9bd4-46fa-8b0d-45f822a32073.png)
![Screenshot 2023-04-18 210413](https://user-images.githubusercontent.com/18661613/232879793-104fe0dc-6640-4cc6-9fba-b919a7be104e.png)

### Version

1.7.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
We fixed one thing related to this in main that you can try, if you're still experiencing please let us know.

**Comment by hwfanatic** [comment]
The second aspect of this issue appears to have been resolved in 1.8.0-rc1. I am able to disconnect nodes without fear of my GUI becoming unusable.

The first aspect of this issue appears to have been reduced, however there are still some nodes in the list without an active connection in the system. Definitely not as many as before.

![Screenshot 2023-04-24 184204](https://user-images.githubusercontent.com/18661613/234062920-228f6557-f458-44d4-974d-2083e095bb13.png)
![Screenshot 2023-04-24 184317](https://user-images.githubusercontent.com/18661613/234062925-a00d68ac-376f-418d-8265-ff2ce62e608b.png)

**Comment by emlowe** [comment]
Closing fixed in 1.8.0 - feel free to reopen or comment if further bugs appear

**Comment by hwfanatic** [comment]
The problem still exists in some shape or form. Admittedly it is now very rare. I'm attaching the last 500 lines from the debug.log but I don't think there is anything related in there. The client was restarted and these errors and warnings are pretty much "standard". Take a look at the screenshots.

![Screenshot 2023-05-05 193849](https://user-images.githubusercontent.com/18661613/236532841-48f63f06-0fb4-415e-84ad-a42f5852fef0.png)

![Screenshot 2023-05-05 194244](https://user-images.githubusercontent.com/18661613/236532857-3ef0f2d0-9505-4423-b79a-81297cb6bcb9.png)

[debug-excerpt.log](https://github.com/Chia-Network/chia-blockchain/files/11408907/debug-excerpt.log)

**Comment by hwfanatic** [comment]
Another one.

![Screenshot 2023-05-26 162239](https://github.com/Chia-Network/chia-blockchain/assets/18661613/cc930c17-eecf-4005-b27a-c15ea7fcc17c)
![Screenshot 2023-05-26 163313](https://github.com/Chia-Network/chia-blockchain/assets/18661613/6dd8888c-ce33-45cd-aa4b-d470ca9bc5eb)

It happened around 16:00 and there are no errors in the log.

2023-05-26T16:01:52.455 full_node full_node_server        : WARNING  Banning 98.43.155.32 for 10 seconds
2023-05-26T16:01:52.456 full_node full_node_server        : WARNING  Incompatible network ID. Maybe the peer is on another network
2023-05-26T16:21:42.154 full_node chia.full_node.full_node: WARNING  Block validation time: 2.13 seconds, pre_validation time: 0.41 seconds, cost: 5491472494, percent full: 49.922% header_hash: 2ef89de240780838f2b82e31af3b871271d188d0599c6cda1c04a90c33253be0 height: 3716060
2023-05-26T16:22:17.024 full_node chia.full_node.full_node: WARNING  Block validation time: 2.18 seconds, pre_validation time: 0.47 seconds, cost: 5495782126, percent full: 49.962% header_hash: 18a7b3f179a37b2aa3dddcecbb2c53ee12ab37dae0633ab121dd73e0336c222a height: 3716062
2023-05-26T16:22:58.105 full_node chia.full_node.full_node: WARNING  Block validation time: 2.13 seconds, pre_validation time: 0.40 seconds, cost: 5219411929, percent full: 47.449% header_hash: 1d6796cc41f3bceadf54a1a57b76943498668693ba3cc5724eac199e65618fc8 height: 3716064
2023-05-26T16:23:54.622 full_node chia.full_node.full_node: WARNING  Block validation time: 2.02 seconds, pre_validation time: 0.30 seconds, cost: 5354561710, percent full: 48.678% header_hash: fca105ec14a34fcd47424940c0287acbb874b724248ad3353e424f90fa9c68fc height: 3716066
2023-05-26T16:30:04.806 full_node chia.full_node.full_node: WARNING  Block validation time: 2.05 seconds, pre_validation time: 0.44 seconds, cost: 5251106681, percent full: 47.737% header_hash: 9345813a9ef87b66d849aae60b34718139df9b9c2b6b51855b756edc47de67cb height: 3716086
2023-05-26T16:30:41.831 full_node chia.full_node.full_node: WARNING  Block validation time: 3.27 seconds, pre_validation time: 0.57 seconds, cost: 5296076645, percent full: 48.146% header_hash: d9bf6f46705c67962b6d690d00020d5bad553b17aea934c3533d81d357ee91ae height: 3716088
2023-05-26T16:31:51.306 full_node chia.full_node.full_node: WARNING  Block validation time: 2.05 seconds, pre_validation time: 0.44 seconds, cost: 5455653039, percent full: 49.597% header_hash: fffcb756e21fafdfcfe5e3d920fae0089a38f694f2b0611e809b5f890b67efbb height: 3716093

**Comment by hwfanatic** [comment]
Are you going to reopen this issue, or do I need to create a new one?!

It's happening at least once a day now, when I'm disconnecting peers with old clients stuck at height 3228000 and 3455000. It's annoying that every 5-10 disconnects it fails with a message, disables the GUI, and I have to restart the app.
