### ISSUE TITLE
[Bug] Chia-blockchain-cli_2.5.0-1_amd64.deb suddenly started crashing on startup

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [Chia-Network/chia-blockchain#19251]
### What happened?

I'm using an Arch Linux binary package, which is just a repackaged version of the mentioned-in-the-title .deb package
https://aur.archlinux.org/packages/chia-cli-bin

It has worked faultlessly since its release, but suddenly started crashing on startup, obviously broken by some package update. It already crashed when I stopped the farmer for kernel update and reboot, but has not worked since.

Python is version 3.13.1

### Version

2.5.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
madmax@[kokoro]:~ # chia start farmer
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/cmds/beta.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/cmds/beta_funcs.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/cmds/cmds_util.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/rpc/farmer_rpc_client.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/rpc/farmer_rpc_api.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/farmer/farmer.py", line 20, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/plot_sync/delta.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/protocols/harvester_protocol.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/types/blockchain_format/proof_of_space.py", line 9, in <module>
ImportError: libbladebit_harvester-493b39b7.so: cannot enable executable stack as shared object requires: Invalid argument
[1429] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by BrandtH22** [comment]
Hey @cyberpunkrocker-zero ,

Thank you for the report, this is a known issue that is fixed in 2.5.1 RC2:
https://github.com/Chia-Network/chia-blockchain/releases/tag/2.5.1-rc2

You can either use the cli specific build there or wait until the actual release of 2.5.1 is available.

Let us know if any questions arise in the meantime. 
Thank you and make it an excellent day,
Brandt H

**Comment by cyberpunkrocker-zero** [comment]
I'm still getting the same error on chia-blockchain-cli-2.5.1-rc2. What now?

**Comment by emlowe** [comment]
Sorry made a mistake - it's in `RC3`  - specifically the fix is in chiapos 2.0.9 proper and RC2 uses `2.0.9rc1`

RC3 has `chiapos 2.0.10` and it does include the stack clearing fix

**Comment by cyberpunkrocker-zero** [comment]
Thanks, it works now!
