### ISSUE TITLE
Connecting to wallet..................

### ISSUE THREAD

**Issue by qwerty051** [Chia-Network/chia-blockchain#2269]
![Безымянный](https://user-images.githubusercontent.com/82948356/115551871-504d7a80-a2b4-11eb-88b9-cf55cc927399.png)

**Comment by lukyrys** [comment]
+1

**Comment by lukyrys** [comment]
```
Traceback (most recent call last):
  File "chia\daemon\server.py", line 954, in <module>
  File "chia\daemon\server.py", line 950, in main
  File "chia\daemon\server.py", line 944, in run_daemon
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\daemon\server.py", line 936, in async_run_daemon
  File "chia\daemon\server.py", line 144, in start
  File "websockets\server.py", line 965, in __await_impl__
  File "asyncio\base_events.py", line 1389, in create_server
OSError: [Errno 10013] error while attempting to bind on address ('127.0.0.1', 55400): an attempt was made to access a socket in a way forbidden by its access permissions
[9508] Failed to execute script server
```

**Comment by saschaeggi** [comment]
+1

**Comment by Heivor** [comment]
> +1
> I'm also getting the "Connecting to wallet" screen.
> Looking in the Console => main.js:1 Already connected, not reconnecting.
Same

**Comment by philtreF** [comment]
+1

**Comment by udidi** [comment]
Same

**Comment by drakunov** [comment]
Same, 1.1.2 

How to repeat
1) Logged in for 1 st time, started plotting
2) i have opened Keys section
3) Stuck there, because no any back button
4) Pressed Reload in Electron Menu

Connecting to wallet....
....
Plotting is active
I have tried different restarts in command line

How to completely restart GUI without stopping plotting?

**Comment by ril3y** [comment]
I have the same issue.

**Comment by philtreF** [comment]
I even tried to delete everything from computer including the .chia folder with settings and keys, reinstall the software and the issue persists... Does someone know how to get out of this issue?

**Comment by oktaysar16** [comment]
Stop Chia (Kill Task)

Delete these folders:
C:\Users\yourusername\.chia
C:\Users\yourusername\AppData\Local\chia-blockchain
C:\Users\yourusername\AppData\Roaming\Chia Blockchain

Reinstall Chia. It should now work.

**Comment by alexs20** [comment]
> Stop Chia (Kill Task)
> 
> Delete these folders:
> C:\Users\yourusername.chia
> C:\Users\yourusername\AppData\Local\chia-blockchain
> C:\Users\yourusername\AppData\Roaming\Chia Blockchain
> 
> Reinstall Chia. It should now work.

It doesn't help

**Comment by philtreF** [comment]
Yeah I confirm that this doesn't help. Like I wrote before : I even tried to delete everything from computer including the .chia folder with settings and keys. Actually I made a new try, I deleted also some Chia-related registry keys and even that did not help. 
There is nothing else to do other than waiting until the developers see this issue and somehow look into this...

**Comment by oktaysar16** [comment]
May work for some and wont work for others. I already posted this work around to Reddit posts with same issue and it has already helped multiple people.

**Comment by SrAp0** [comment]
> Para ver la lista de puertos bloqueados en Windows, use:
> `netsh interface ipv4 show excludedportrange protocol=tcp`
> 
> Si el puerto 55400 es esa lista de rangos de puertos, use:
> `net stop winnat`
> [start chia]
> `net start winnat`

Thx! It worked for me, I had this error on 2 computers and it was fixed.
This was the error I got (File "websockets \ protocol.py", line 827, in transfer_data
  File "websockets \ protocol.py", line 895, in read_message
  File "websockets \ protocol.py", line 971, in read_data_frame
  File "websockets \ protocol.py", line 1051, in read_frame
  File "websockets \ framing.py", line 105, in read
  File "asyncio \ streams.py", line 679, in readexactly
  File "asyncio \ streams.py", line 473, in _wait_for_data
  File "asyncio \ selector_events.py", line 870, in write
ConnectionResetError: [WinError 10054] An existing connection has been forced to interrupt by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia \ daemon \ server.py", line 187, in safe_handle
  File "websockets \ protocol.py", line 555, in send
  File "websockets \ protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason)
Thanks again :D!

**Comment by ramcsamal** [comment]
> To see the list of blocked ports in windows use:
> `netsh interface ipv4 show excludedportrange protocol=tcp`
> 
> If port 55400 is that list of port ranges use:
> `net stop winnat`
> [start chia]
> `net start winnat`

Thanks, it worked.

**Comment by DennisYildirim** [comment]
when I type that command, it shows the ports below. And 55400 is not blocked at all. And it simply does not solve the problem at all. 

C:\Users\buzad>netsh interface ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      5357        5357
      5426        5426
     49780       49879
     49880       49979
     50000       50059     *
     50060       50159
     50160       50259
     50260       50359
     50510       50609
     50610       50709
     50710       50809
     50810       50909
     50910       51009
     54235       54235
     54236       54236

* - Administered port exclusions.


C:\Users\buzad>
C:\Users\buzad>
