### ISSUE TITLE
[BUG] Memory leak in daemon

### ISSUE THREAD

**Issue by hcieslewicz** [Chia-Network/chia-blockchain#3366]
**Description**
After running chia plotting for 2 days, the daemon.exe reached 42GB of memory.

**To Reproduce**
Use 3 HDD with three regular queues and one SSD for one parallel plotting. Use default plotting settings. For parallel plotting give 120min delay. Leave it for 2 days.

**Expected behavior**
Daemon should not use so much of memory. I was expecting max usage for all Chia processes about 28GB total ( around 8 chia plots x 3390MiB max memory usage)

**Screenshots**
![image](https://user-images.githubusercontent.com/42321310/116795045-57edfa00-aad2-11eb-91a4-08fdb72462a7.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- RAM: 64 GB
- Chia version: 1.1.2

**Comment by mariano54** [comment]
This is fixed in 1.1.3

**Comment by bandit8623** [comment]
not fixed.  after a day or so the gui uses a ton of ram.  in my case it was using over 60GB and crashes the client.  my plotters are still going though.  this happened today on 1.1.5.   also happened on 1.1.4

**Comment by jhstatewide** [comment]
Confirmed not fixed in 1.1.5. Linux/ARM

**Comment by denisprovost** [comment]
![Capture](https://user-images.githubusercontent.com/10295449/131860409-aa06e10e-9cdb-4cde-9b12-724288f938f8.jpg)
