### ISSUE TITLE
[BUG]How to generate coin_info

### ISSUE THREAD

**Issue by xianggy** [Chia-Network/chia-blockchain#3944]
coinID == sha256(parent_ID + puzzlehash + amount)
I found it from https://chialisp.com/docs/doc2

I tried it with Nodejs and still not correct.
console.log(CryptoJS.SHA256('f7e09a94c5da73019577b288aeedaf4750540ecca091bb5c4bcf45dacb3a0485' + 'ee12091f293040e42999c64d471ec9a65692f1dde0c42a4936d80e25a8d0535c' + 299700000000).toString()) // return e8ad8111fd2761792b9b39a531117ca8edcbc4ba65b2c3d9472c63dd76876731 not matched 6dddefd62523efccacf35e0cac24cc5348dde8f40ae48be1c563a9404e8251fe

So what the type of these params are?
Can someone provide any examples? Thank you.

**Comment by xianggy** [comment]
Fixed it in Nodejs.
```
//let CryptoJS = require("crypto-js"); // not work
let crypto = require('crypto')
let getCoinInfo = function(parent_coin_info, puzzle_hash, amount) {
    let a = Buffer.from(parent_coin_info, 'hex')
    let b = Buffer.from(puzzle_hash, 'hex')
    let c = Buffer.from((amount).toString(16), 'hex')
    let d = Buffer.concat([a, b, c], a.length + b.length + c.length);
    const hash = crypto.createHash('sha256')
    hash.update(d)
    return hash.digest('hex')
}
console.log(getCoinInfo('f7e09a94c5da73019577b288aeedaf4750540ecca091bb5c4bcf45dacb3a0485', 'ee12091f293040e42999c64d471ec9a65692f1dde0c42a4936d80e25a8d0535c', 299700000000))
```

**Comment by crcrcr999** [comment]
Still have problem,watch [this:](https://www.chiaexplorer.com/blockchain/coin/0x35bbe3ad5bed7165e4837124a7df8f9a7363a519f4ade8920af9315fb6326e09)
`console.log(getCoinInfo('66b5ee60a2cbba93951a534cfa76d31adc98542dcc5bac95e63572fbaf652576', '38b99b01362d6bb46d2cb55b8a04b73bea29a4dc565061be9eb79aead7a064d6', 1100000000))`
return correct value ‘35bbe3ad5bed7165e4837124a7df8f9a7363a519f4ade8920af9315fb6326e09’

but this [https://www.chiaexplorer.com/blockchain/coin/0x5615ca8684e921b6bf2c0542bd5f878df62bf3c0154856a2793eae5167a17461](https://www.chiaexplorer.com/blockchain/coin/0x5615ca8684e921b6bf2c0542bd5f878df62bf3c0154856a2793eae5167a17461)
or this [https://www.chiaexplorer.com/blockchain/coin/0xf48e1a969fe4d4fbb361c9afa89e2f2d3ad30434013873ea601d2895b6cb6e94](https://www.chiaexplorer.com/blockchain/coin/0xf48e1a969fe4d4fbb361c9afa89e2f2d3ad30434013873ea601d2895b6cb6e94)
return wrong value

**Comment by litterGuy** [comment]
Use coinID == sha256(parent_ID + puzzlehash + amount) to generate coinId.
It has been generated correctly until I run into this : https://www.chiaexplorer.com/blockchain/coin/0xa48ae3986b5a27e7d46608ea91dea2b097127a4a21a04507c28aee33222a776f

```
amount : 2300000000
parent_coin_info : 0xadc79e3d3295eb6e32c138f0f0c3466344bb7be31c0ffb02861c4189fd9942d5
puzzle_hash : 0xb39e0ae17737489a080d9693759b7af709a0ee56ba885acd2dae9f1f3ca67092
```

Generated is ：0xabee1e7951df211c1bdd077506b551b5fbe7d2ca00086e8a208160d6f0f56242

Where is the problem？
