### ISSUE TITLE
[help] HARVESTER MACHINE LOGS SAYING :Cannot connect to host 192.168.10.2:8447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1091)')]

### ISSUE THREAD

**Issue by tksalarzai** [Chia-Network/chia-blockchain#4347]
**Describe the issue**
2021-05-10T01:31:49.910 harvester harvester               : INFO     Started harvester service on network_id: mainnet
2021-05-10T01:31:49.918 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.10.2', 'port': 8447}
2021-05-10T01:31:49.990 harvester harvester_server        : INFO     Cannot connect to host 192.168.10.2:8447 ssl:True **[SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1091)')]**
2021-05-10T01:31:50.014 daemon chia.daemon.server         : INFO     Register service {'service': 'chia_harvester'}
2021-05-10T01:31:50.022 daemon chia.daemon.server         : INFO     registered for service chia_harvester
2021-05-10T01:31:50.030 daemon chia.daemon.server         : INFO     {'success': True}
2021-05-10T01:31:53.016 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.10.2', 'port': 8447}
2021-05-10T01:31:53.042 harvester harvester_server        : INFO     Cannot connect to host 192.168.10.2:8447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1091)')]
2021-05-10T01:31:56.062 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.10.2', 'port': 8447}
2021-05-10T01:31:56.086 harvester harvester_server        : INFO     Cannot connect to host 192.168.10.2:8447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1091)')]
2021-05-10T01:31:59.104 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.10.2', 'port': 8447}
2021-05-10T01:31:59.120 harvester harvester_server        : INFO     Cannot connect to host 192.168.10.2:8447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1091)')]
2021-05-10T01:32:02.152 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.10.2', 'port': 8447}
2021-05-10T01:32:02.160 harvester harvester_server        : INFO     Cannot connect to host 192.168.10.2:8447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1091)')]
2021-05-10T01:32:05.182 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.10.2', 'port': 8447}
2021-05-10T01:32:05.190 harvester harvester_server        : INFO     Cannot connect to host 192.168.10.2:8447 ssl:True [SSLCertVerificationError: (1, '
![Screenshot 2021-05-10 013744](https://user-images.githubusercontent.com/77279839/117586253-76866d80-b130-11eb-9ce0-3bb7101d97b5.png)
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1091)')]
2021-05-10T01:32:08.202 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.10.2', 'port': 8447}
2021-05-10T01:32:08.202 harvester harvester_server        : INFO     Cannot connect to host 192.168.10.2:8447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1091)')]

![Screenshot 2021-05-10 013804](https://user-images.githubusercontent.com/77279839/117586250-6a9aab80-b130-11eb-8076-53e1329040b4.png)

**Comment by tksalarzai** [comment]
SOLVED BY THIS
![image](https://user-images.githubusercontent.com/77279839/117587464-85bce980-b137-11eb-9a6b-8b99c5189b13.png)

**Comment by zylv3r** [comment]
Tried recopying the certs, but still having the issue, any other solutions?
