### ISSUE TITLE
[BUG] 1.2.0 Pool SSL Certificate Failed to verify

### ISSUE THREAD

**Issue by Biggers78** [Chia-Network/chia-blockchain#7273]
**Describe the bug**

Cannot connect to host xch.spacefarmers.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]

Certificate validity appears correct at both ends.

Result:  Pool creates, Contract and ID.  However not connected to pool, unable to get plot points

**To Reproduce**

chia.net download
Installed
Synced then pool added.  Thats it.

From my basic understanding it appears to be a Python issue, but I'm far from an expert.

Tested on two different machines / MAC OS Big Sur 11.4 & Catalina 10.15.7

**Expected behavior**
To work...

**Screenshots**
N/A

**Desktop**

- OS: MAC OSX
- OS Version/Flavor: 1. Bur Sur 11.4 - 2. Catalina 10.15.7
- CPU: 1. Inel i7 - 2.  Intel i5

**Additional context**

**Comment by loppefaaret** [comment]
could you try a fresh reinstall, we had a PR submitted on our CA cert yesterday that should fix this

**Comment by yshklarov** [comment]
> could you try a fresh reinstall, we had a PR submitted on our CA cert yesterday that should fix this

The fresh CA cert didn't make it into the 1.2.0 package. But in any case, replacing it with the newer file doesn't resolve the issue (I tested this). The problem is that the cert isn't being used. See my notes in the duplicate bug report.

**Comment by Biggers78** [comment]
I Stopped the GUI and and reinstalled.  This did not fix the issue.  I will uninstall, delete all files and resync.  Will report again later.

**Comment by loppefaaret** [comment]
yes, my bad, i guess that fix above does not work for using the installers - you need to await a 1.2.1

**Comment by roxleopardo** [comment]
I'm having the same issue. I'm using Manjaro Linux distro (Arch Linux based) and Python 3.9.5.

**Comment by loppefaaret** [comment]
@roxleopardo thank you very much for the report.
on that node, im closing this issue, and participants should await a 1.2.1 release for a fix for installer users

**Comment by youngfong13** [comment]
> yes, my bad, i guess that fix above does not work for using the installers - you need to await a 1.2.1

Would 1.2.1.dev0 or later have this fixed?

**Comment by loppefaaret** [comment]
please don't run dev releases on mainnet, without express direction from a developer - it can cause unexpected results!

**Comment by Biggers78** [comment]
I will wait for 1.2.1.

Hopefully early next week so I can then connect to the pool correctly.

**Comment by youngfong13** [comment]
> please don't run dev releases on mainnet, without express direction from a developer - it can cause unexpected results!

Okay, just looking for solutions. so far 1.2.0 doesn't work for pool plots on linux/Mac OS for me and my non-pool plots aren't recognized in CLI.

**Comment by ukrainets** [comment]
I'm also having this issue, (Mac OS 11.4 ) and according to messages in the Space pool discord, a lot of people have it.
@loppefaaret can you share any gestimation on when we can expect a v1.2.1 ?

**Comment by loppefaaret** [comment]
I'm sorry, but all i can say is soon, hopefully very soon

**Comment by griffithJ** [comment]
Still broken on Mac in release 1.2.1

    % chia version
    1.2.1
    % grep "GET /pool_info" debug.log | tail -1                                             
    2021-07-12T14:40:18.381 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://chia.futurepool.io, Cannot connect to host chia.futurepool.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]

**Comment by loppefaaret** [comment]
@griffithJ is that installer ? m1(arm) or intel based ?

**Comment by griffithJ** [comment]
> @griffithJ is that installer ? m1(arm) or intel based ?

That was the .app copied from the .dmg. Intel. Is there a better way I should be installing updates?

**Comment by loppefaaret** [comment]
that is perfect, just wanted to make sure the error was in the installer!

**Comment by StonedStudio** [comment]
I have the issue as well still on 1.2.1 using the m1 installer.

**Comment by ukrainets** [comment]
Yes me too. I just installed 1.2.1 and still see the same issue
`2021-07-12T17:58:06.798 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]`

When I go to check the Pool login link I get this message
https://twitter.com/FarmChia/status/1414721726869606402/photo/1

**Comment by loppefaaret** [comment]
> > could you try a fresh reinstall, we had a PR submitted on our CA cert yesterday that should fix this
> 
> The fresh CA cert didn't make it into the 1.2.0 package. But in any case, replacing it with the newer file doesn't resolve the issue (I tested this). The problem is that the cert isn't being used. See my notes in the duplicate bug report.

i think yshklarov might have something here from his dupe #7278  I'm escalating this up the chain to get some 👀 on it

**Comment by Biggers78** [comment]
I got a fix yesterday

You need to upgrade the python version, I suspect it is still 2.7.

Install brew https://brew.sh/ <https://brew.sh/>

Upgrade to 3.9.5 see here https://opensource.com/article/19/5/python-3-default-mac <https://opensource.com/article/19/5/python-3-default-mac> (note:  change 3.7.3 to 3.9.5)

Then run 

pip3 install --upgrade certifi

This will fix it :-)

**Comment by andrewsno1** [comment]
I am getting the same error when trying to create a plotnft:

`Exception from 'wallet' Error connecting to pool https://pool.chiahub.io: Cannot connect to host pool.chiahub.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]
`

I am running version 1.2.1 on Manjaro Linux. I had the issue with version 1.2.0. I tried to connect to https://pool.chiahub.io

**Comment by ukrainets** [comment]
@loppefaaret Yesterday I tried a clean install with the intel Mac GUI installer and it didn't work, still have the same issue.
Doing clean install via CLI was my last hope that what I'll try to do today and will use @Biggers78 suggestion.

**Comment by StonedStudio** [comment]
I also no longer have an issue once Python was adjusted to 3.#. It appears to have defaulted to use 2.7

**Comment by bernharl** [comment]
Still have the issue on Arch Linux. python-certifi installed.

**Comment by ukrainets** [comment]
I fixed this issue on my farmer machine by updating python.

**Comment by yshklarov** [comment]
Release 1.2.2 fully resolves the issue on my system (arch linux). Thanks @loppefaaret @emlowe @wjblanke!

**Comment by emlowe** [comment]
Fixed in 1.2.2

**Comment by Manintorn** [comment]
I fixed this problem by update Python 3.9.5 and Chia 1.2.2

**Comment by KmBooy** [comment]
Does Windows 10 have this problem

**Comment by Manintorn** [comment]
> Does Windows 10 have this problem

My PC with Windows10 works just fine.

**Comment by njtnestor** [comment]
I have the same problem in 1.2.2

**Comment by andrewsno1** [comment]
> I am getting the same error when trying to create a plotnft:
> 
> `Exception from 'wallet' Error connecting to pool https://pool.chiahub.io: Cannot connect to host pool.chiahub.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')] `
> 
> I am running version 1.2.1 on Manjaro Linux. I had the issue with version 1.2.0. I tried to connect to https://pool.chiahub.io

Fixed for me in 1.2.2
I am plotting for the pool now.

**Comment by hlung** [comment]
For me, something was messing my DNS. I go to System Preferences > Network > select my wifi > DNS tab > add `8.8.8.8` to my DNS servers list. This solves the issue for me.
