### ISSUE TITLE
[BUG] Cannot connect to host 127.0.0.1:8444 ssl

### ISSUE THREAD

**Issue by Dartellum** [Chia-Network/chia-blockchain#7458]
**Describe the bug**
 Second upgrade to latest results in the farm not working. Last time I needed to delete the dbs and let sync from beginning. I tried a backed up db and also had same error. 

**Now I am down for days while it syncs again.**

**To Reproduce**

1. Upgrade to latest.
2. Start Farm
4. Open debug.log and see errors

**Expected behavior**
 Connect to farmer.

**Screenshots**

```
2021-07-13T14:29:20.291 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:23.021 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:23.024 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:23.293 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:23.295 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:26.026 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:26.028 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:26.296 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:26.298 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:29.029 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:29.030 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:29.300 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:29.301 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:32.031 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:32.033 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:32.303 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:32.305 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:34.704 wallet chia.wallet.wallet_node    : INFO     Validated, fork point is 565645
2021-07-13T14:29:34.705 wallet chia.wallet.wallet_node    : INFO     self.sync_event.set()
2021-07-13T14:29:34.779 wallet chia.wallet.wallet_node    : INFO     Have collected 1 potential peaks
2021-07-13T14:29:35.035 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:35.040 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:35.308 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:35.315 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:36.680 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 565644-565676
2021-07-13T14:29:38.042 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:38.045 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:38.318 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:38.322 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:41.046 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:41.048 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:41.080 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 565676-565708
2021-07-13T14:29:41.323 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:41.326 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
2021-07-13T14:29:44.049 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-13T14:29:44.050 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7>
```

**Desktop**

- OS:  Linux
- OS Version/Flavor:  Ubuntu 20.04.2
- CPU:  Intel i7 3770k

**Additional context**

**Comment by Dartellum** [comment]
Seems 1.2.2 fixed this. However, now I have a new challenge, see https://github.com/Chia-Network/chia-blockchain/issues/7503

**Comment by LineToAnyWhere** [comment]
I have the same problem，it's likely wallet not start 8444 port

**Comment by Dartellum** [comment]
> I have the same problem，it's likely wallet not start 8444 port

The wallet was started as I tried to start it again.

**Comment by Dartellum** [comment]
> Seems 1.2.2 fixed this. Edit: Nope, still happening and not syncing. I need to rm the databases again.
> 
> However, now I have a new challenge, see #7503

I am still syncing.... ridiculous the upgrades do this. Checking the debug.log right now, I see I am only using 4 peers now to sync. When I started the sync, I had about 65 peers I was syncing from. Present: `Syncing 405810/571887` and this is outdated now too.

**Comment by dowoco** [comment]
I find that I have shutdown the chia client and restart it to fix this issue in Windows 10 running 1.2.2 client. But this only fixes the issue for a few hours. Then the "Cannot connect to host 127.0.0.1:8444 ssl" issue re-surfaces in the logs and wallet stops syncing. Could it be that it times-out the wallet service when copying over plots from another plotter? The network could get overloaded and the Wallet service crashes?
I also find that when this happens I start sending Invalid Partials to the pool. So I have no choice but the restart the whole client every few hours.

**Comment by Dartellum** [comment]
> I find that I have shutdown the chia client and restart it to fix this issue in Windows 10 running 1.2.2 client. But this only fixes the issue for a few hours. Then the "Cannot connect to host 127.0.0.1:8444 ssl" issue re-surfaces in the logs and wallet stops syncing. Could it be that it times-out the wallet service when copying over plots from another plotter? The network could get overloaded and the Wallet service crashes?
> I also find that when this happens I start sending Invalid Partials to the pool. So I have no choice but the restart the whole client every few hours.

I copy files over to this machine from another one. I did notice that on some nights around midnight local time Verizon does something and I temporary lose Internet. I have 1Gb FIOS. Sometimes it is just a blip and sometimes a few minutes. My IP on my router does not change. :man_shrugging: This feels like the old Windows 95/98 days where the answer once to restart the computer.

**Comment by spencerhite** [comment]
I’m in the same boat, I’ve tried two separate db/wallet-db from two separate full nodes and I receive ‘cannot connect to host 127.0.0.1:8444’ when attempting to use either of them. I really don’t want to start from scratch.

**Comment by zlatovlas** [comment]
I am facing the same issue.

Details of the system:
- port forwarded correctly, UPnP disabled in conf, multiple cores reserved for chia (even tried four), computer connected via Ethernet, Ubuntu 20.04.2, fully updated, Chia 1.2.2.

I noticed that it gets worse when I copy new NFT plots to the disks, however can be a coincidence. Now I am struggling to stay synced for more than two hours. Different computer is used for plotting.

Log looks the same, chia just hangs.

**Comment by dowoco** [comment]
> I am facing the same issue.
> 
> Details of the system:
> 
> * port 8444 forwarded correctly, UPnP disabled in conf, multiple cores reserved for chia (even tried four), computer connected via Ethernet, Ubuntu 20.04.2, fully updated, Chia 1.2.2, blockchain on SSD.
> 
> I noticed that it gets worse when I copy new NFT plots to the disks, however can be a coincidence. Now I am struggling to stay synced for more than two hours. Different computer is used for plotting.
> 
> Log looks the same, chia just hangs.
> 
> Update 1:
> 
> 1. I deleted blockchain_v1_mainnet.sqlite and blockchain_wallet_v1_mainnet_*.sqlite
> 2. Started the daemon (./chia start farmer).
> 3. In like 7 minutes I got the following message in debug.log:
> 
> > 42021-07-20T16:47:58.594 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id:a8351e5317c74960fc53c88a29d3d94d20cdac56e10fcac3ae375fb2b0a16d7a
> > 2021-07-20T16:48:00.642 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444
> 
> 1. And the sync process hangs, the wallet cannot be connected to.
> 
> Update 2:
> 
> 1. I have restarted the computer after kernel & nVidia drivers update.
> 2. Still not solved.
> 3. This is the excerpt from the log I believe is the relevant culprit:
> 
> ` _2021-07-21T18:04:48.937 daemon chia.daemon.server : INFO Websocket exception. Closing websocket with chia_full_node code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last): File "websockets/protocol.py", line 827, in transfer_data File "websockets/protocol.py", line 895, in read_message File "websockets/protocol.py", line 971, in read_data_frame File "websockets/protocol.py", line 1047, in read_frame File "websockets/framing.py", line 105, in read File "asyncio/streams.py", line 723, in readexactly File "asyncio/streams.py", line 517, in _wait_for_data asyncio.exceptions.CancelledError The above exception was the direct cause of the following exception: Traceback (most recent call last): File "chia/daemon/server.py", line 172, in safe_handle File "websockets/protocol.py", line 439, in **aiter** File "websockets/protocol.py", line 509, in recv File "websockets/protocol.py", line 812, in ensure_open websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason `
> `2021-07-21T18:04:52.912 farmer farmer : INFO Reconnecting to peer {'host': '127.0.0.1', 'port': 8444} `
> 
> Update 3:
> 
> 1. I gave up, deleted the content of folders db/ and wallet/ and restarted.
> 2. After 8 hours I am synched at 263k. More than half to go still.

Did this fix the issue? Has the wallet db been corrupted after upgrading from 1.17 to 1.2x? How long has your wallet sync now been stable?

**Comment by zlatovlas** [comment]
> Did this fix the issue? Has the wallet db been corrupted after upgrading from 1.17 to 1.2x? How long has your wallet sync now been stable?

Hello,

1. the issue is not fixed by resync.
2. during the re-sync I had to restart the whole computer once.
3. after that it looked promising and it worked for over 19 hours.
4. then the same thing happened, even ./chia start -r wallet did not resolve it.

<code>
this` might be the relevant log part:
2021-07-23T11:57:00.660 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 392046, weight 102711232,
2021-07-23T11:57:00.990 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: acbad7afdf7df83e165ee7aaf55ab9fec36752d0737a80d91ae54323d73ee10e
2021-07-23T11:57:00.991 full_node chia.full_node.full_node: INFO     peer disconnected None
2021-07-23T11:57:01.049 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_wallet code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets/protocol.py", line 827, in transfer_data
  File "websockets/protocol.py", line 895, in read_message
  File "websockets/protocol.py", line 971, in read_data_frame
  File "websockets/protocol.py", line 1047, in read_frame
  File "websockets/framing.py", line 105, in read
  File "asyncio/streams.py", line 721, in readexactly
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 172, in safe_handle
  File "websockets/protocol.py", line 439, in __aiter__
  File "websockets/protocol.py", line 509, in recv
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
</code>

I am out of ideas. :/ Unless this really is a bug.

**Comment by zlatovlas** [comment]
Unfortunately, it happened again, in like 13 hours. The error stays the same.

**Comment by bwoodworth** [comment]
I have the same issue.  Everything starts normally, but after some time it start getting the same logs and it stops syncing and farming.

**Comment by setar** [comment]
+1 
my last working code is 0c35b7718d1ba505130ddb861114d9dabcc19a23 @main

**Comment by setar** [comment]
this work for me :
```
(venv) chia@main:~/chia-blockchain$ git diff
diff --git a/chia/daemon/server.py b/chia/daemon/server.py
index 82ea5d67..9dcb6ad6 100644
--- a/chia/daemon/server.py
+++ b/chia/daemon/server.py
@@ -145,8 +145,8 @@ class WebSocketServer:
             self.self_hostname,
             self.daemon_port,
             max_size=50 * 1000 * 1000,
-            ping_interval=500,
-            ping_timeout=300,
+            ping_interval=25,
+            ping_timeout=20,
             ssl=self.ssl_context,
         )
         self.log.info("Waiting Daemon WebSocketServer closure")
diff --git a/setup.py b/setup.py
index f048fe70..938550c8 100644
--- a/setup.py
+++ b/setup.py
@@ -6,7 +6,7 @@ dependencies = [
     "chiabip158==1.0",  # bip158-style wallet filters
     "chiapos==1.0.4",  # proof of space
     "clvm==0.9.7",
-    "clvm_rs==0.1.8",
+    "clvm_rs==0.1.10",
     "clvm_tools==0.4.3",
     "aiohttp==3.7.4",  # HTTP server for full node rpc
     "aiosqlite==0.17.0",  # asyncio wrapper for sqlite, to store blocks
@@ -21,7 +21,7 @@ dependencies = [
     "PyYAML==5.4.1",  # Used for config file format
     "setproctitle==1.2.2",  # Gives the chia processes readable names
     "sortedcontainers==2.3.0",  # For maintaining sorted mempools
-    "websockets==8.1.0",  # For use in wallet RPC and electron UI
+    "websockets==9.1",  # For use in wallet RPC and electron UI
     "click==7.1.2",  # For the CLI
     "dnspython==2.1.0",  # Query DNS seeds
 ]

```

**Comment by hejz0r** [comment]
`2021-08-28T14:26:09.221 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001DE33472640> [Określona nazwa sieciowa już jest niedostępna]`

Wallet can't sync ... running since april, stopped yesterday o.O

**Comment by levidurfee** [comment]
> ```
> 2021-08-28T14:26:09.221 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001DE33472640> [Określona nazwa sieciowa już jest niedostępna]
> 
> 2021-08-28T14:26:10.219 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000023B00DA1640> [Określona nazwa sieciowa już jest niedostępna]
> ```
> 
> Wallet can't sync ... running since april, stopped yesterday o.O

Mine also stopped yesterday after running for a month.

**Comment by emlowe** [comment]
This might be related to #8307

**Comment by ALTracer** [comment]
> This might be related to #8307

Barely. 8307 is a non-fatal slow memory leak. My wallet syncs just fine on 1.2.5.
7458 occurs because full_node fails to start up and `LISTEN` on :8444. Nobody had sent `netstat` output here, so I can't say for sure.

To the affected: launch only `chia start node` and watch level=INFO debug logs if full_node starts up at all.

**Comment by levidurfee** [comment]
## Farmer

* https://i.imgur.com/D4UQYmT.png
* https://i.imgur.com/3OQjho9.png

## Harvester

* https://i.imgur.com/FY7vLrq.png
* https://i.imgur.com/BOWTKRk.png

I wish I knew what was happening :(

**Comment by Budje70** [comment]
I have the same issue.
I used to use client 1.1.7
Yesterday updated the cliënt to 1.2.7. Since then my wallet is not able to sync and shows 0 xch.
The log continuesly showing "Cannot connect to host 127.0.0.1:8444".
Firewall temporarly disabled to see if it helped. It isn't.

**Comment by greg-fischer** [comment]
Same here. System was hung up today (noticed space pool has almost no space for hours today). Had to reboot the system and now the node will not start.  There's tons of this:
```
Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
```
And netstat shows:
```
tcp      518      0 127.0.0.1:8444          127.0.0.1:60316         CLOSE_WAIT  -                   
tcp      518      0 127.0.0.1:8444          127.0.0.1:60298         CLOSE_WAIT  -                   
tcp      518      0 127.0.0.1:8444          127.0.0.1:60280         CLOSE_WAIT  -                   
tcp      518      0 127.0.0.1:8444          127.0.0.1:60124         CLOSE_WAIT  -                   
tcp      518      0 127.0.0.1:8444          127.0.0.1:60058         CLOSE_WAIT  -                   
tcp      518      0 127.0.0.1:8444          127.0.0.1:60150         CLOSE_WAIT  -                   
tcp      518      0 127.0.0.1:8444          127.0.0.1:60084         CLOSE_WAIT  -                   
tcp      518      0 127.0.0.1:8444          127.0.0.1:60118         CLOSE_WAIT  -                   
tcp      518      0 127.0.0.1:8444          127.0.0.1:60296         CLOSE_WAIT  -                   
tcp      518      0 127.0.0.1:8444          127.0.0.1:60320         CLOSE_WAIT  -  
```
There's probably 50-60 of those.

I tried restarting just the node and got a trace back.
```
OSError: [Errno 98] error while attempting to bind on address ('::', 8444, 0, 0): address already in use
```
Netstat did say chia_full_node running on ::8444 though.  Even after trying chia stop all -d and restarting.  

Just restarted again, tried chia start farmer:
```
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
```
Nothing is on that port.  And I've got IPv6 disabled.
This is a Debian 10 virtual machine.  Not seeing any hardware or journalctl errors.
It looks like this is only attempting IPv6?  That's can't be right?

**Comment by Kricheck** [comment]
I did a lot of things, and finally after giving this command the node start to work again:

.\chia.exe configure --set-farmer-peer 192.168.1.106:8447

Where 192.168.1.106 must be replaced for your node local IP.  I did this trying that node instead of connecting to the IP loopback, it did it to the local IP of the node.

I hope that it works for you too.

**Comment by cross** [comment]
Side note that the PR #8861 will likely fix this, as it introduces a config variable that will return IPv4 (or IPv6 if preferred) addresses first whenever available.  From above, it looked like your host was returning IPv6 first when you didn't expect it to.

**Comment by M6mmix** [comment]
Same problem on 1.2.11 win10. Solutions?

**Comment by thestevekoch** [comment]
Same issue after upgrade to 1.2.11 rpi4 ubuntu.

**Comment by michaelsargent** [comment]
> Same issue after upgrade to 1.2.11 rpi4 ubuntu.
> 
> Running "chia show -a node.chia.net:8444" resolved my issue

Does not resolve mine :(  
Shows:
Connecting to node.chia.net, 8444
Failed to connect to node.chia.net:8444

Tried alternate nodes, same issue.  Fails to connect.

**Comment by michaelsargent** [comment]
> > Same issue after upgrade to 1.2.11 rpi4 ubuntu.
> > Running "chia show -a node.chia.net:8444" resolved my issue
> 
> Does not resolve mine :( Shows: Connecting to node.chia.net, 8444 Failed to connect to node.chia.net:8444
> 
> Tried alternate nodes, same issue. Fails to connect.

3 hours later, and the blank screen with circles is gone and it is not syncing.  I just waiting it out.  It seems the connection issues reported are the ones that fail.  It seems there are many more attempts that connect and are not logged in INFO.  Perhaps we need to ignore INFO fails to connect log entries.

**Comment by nothingshocking** [comment]
I am facing the same issue and need some help. I've been farming since July with no problems but started noticing my farmer would get out of sync and would take a long time to restart and get back up to peak. 

The first approach I took was to address the growing blockchain db size coming close to maxing out my RPi storage. I moved the .chia folder to a drive with plenty of space and increased swap size. Also, updated to the latest Chia version. 

Since then I started to notice the issue on Chia restart the GUI will show "Connecting to Wallet" for 10-30+ mins, at the same time the log will show "Cannot connect to host 127.0.0.1:844 ssl" for quite a long time, and when it finally did connect it would take quite some time to catch up on sync (not very surprising). Based on researching this bug and similar posts I deleted my wallet DB since people indicated corruption could be a cause. The wallet db has been re-syncing for a few days now (ugh). Slowness of that sync aside the very long start up, cannot connect to host, issue has not changed. 

System/Farmer details:
RPi 4, Ubuntu 20.04.2, Chia 1.2.11, 20tb of plots on external HDD, port 8444 forwarded from network firewall to Farmer RPi, UPnP disabled in config, .chia folder and blockchain db on external HDD w symlink. 

`2021-12-01T14:55:07.525 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-12-01T14:55:07.561 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0xffff9a5c7b40> [Connect call failed ('127.0.0.1', 8444)]`

I haven't found any guidance that helped and I can't seem to resolve this cannot connect to local host and LONG start up time issue. I am out of ideas. Does anyone have thoughts on how to address this? What other information would be helpful to know?

**Comment by michaelsargent** [comment]
Has it finished syncing?
With the latest client I see a long delay just to choose the wallet. Then it’s another hour to start syncing (the circles going round and round). Another hour to complete syncing. This is just after a Linux software update and restart. The length of time down affects how long the sync takes.

**Comment by nothingshocking** [comment]
> 

No, unfortunately not and at this rate it will take several more DAYS. 

When I wrote up the issue I restarted everything to confirm my description. That was 45 minutes ago at this point and the GUI still says Connecting to Wallet, I haven't been able to choose my keys/wallet yet. Your description is aligned with my experience. After selecting my key the Main node page on the GUI shows circles/syncing for another LONG period of time. That seems to go away when the connection to the local host finally is established. Then it takes a while to sync the blockchain back up to peak and the wallet sync continues. There is definitely something wrong somewhere. My RPi farmer was working really well until recently.

**Comment by emlowe** [comment]
this is a problem in the node startup - it can take a long time to start (depending on many factors including disk where the DB is) - this likely is not a problem with your wallet. Once the node starts you should see these errors disappear. Everytime you restart, you are causing this issue again. I recommend starting the node only `chia start node` and then waiting for it to start syncing, or otherwise respond to `chia show -s`. This can help diagnose issues, but it likely is that your node is taking a long time to start.

We are working on some enhancements to this. You may want to pull main and see if it helps as PR 8771 was merged and it may help your startup times.

Also, we do not recommend using the GUI on the pi4

**Comment by nothingshocking** [comment]
> this is a problem in the node startup - it can take a long time to start (depending on many factors including disk where the DB is) - this likely is not a problem with your wallet. Once the node starts you should see these errors disappear. Everytime you restart, you are causing this issue again. I recommend starting the node only `chia start node` and then waiting for it to start syncing, or otherwise respond to `chia show -s`. This can help diagnose issues, but it likely is that your node is taking a long time to start.
> 
> We are working on some enhancements to this. You may want to pull main and see if it helps as PR 8771 was merged and it may help your startup times.
> 
> Also, we do not recommend using the GUI on the pi4

Not using the GUI on the Pi4 makes sense and I haven't been until lately only to monitor the wallet sync really. You are right, once the connection is established the connection error isn't recurring.  After reading about 8771 the node startup does sound like the issue. I am a bit of a noob. I am familiar with getting the latest as part of the update process but not clear on how to pull the main.

**Comment by nothingshocking** [comment]
Can anyone help this a noob figure out how to update my node with #8771  as @emlowe suggested?

**Comment by keliew** [comment]
> Can anyone help this a noob figure out how to update my node with #8771 as @emlowe suggested?

Something like this on Linux...
```
$ git clone -b latest https://github.com/Chia-Network/chia-blockchain.git ./
$ git fetch origin pull/8771/head:pr-8771 && git checkout pr-8771
$ chmod +x install.sh
$ ./install.sh
```
Just replace `8771` with any PR number...

**Comment by emlowe** [comment]
Even easier, it's been merged into main - so just `git clone https://github.com/Chia-Network/chia-blockchain.git` which will fetch main for you.

Even easier still - you can download the beta builds from https://www.chia.net/download/

(note you don't want the lite wallet beta)

**Comment by marssystems** [comment]
I just tried the latest  beta build for Windows 10, to see if it fixed this error for me - but it didn't. I still get -

2021-12-02T16:42:19.468 wallet wallet_server              : DEBUG    Connecting: wss://127.0.0.1:8444/ws, Peer info: {'host': '127.0.0.1', 'port': 8444}
2021-12-02T16:42:21.500 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001FAE2AB1F40> [The remote computer refused the network connection]
2021-12-02T16:42:22.020 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8447}
2021-12-02T16:42:22.024 harvester harvester_server        : DEBUG    Connecting: wss://127.0.0.1:8447/ws, Peer info: {'host': '127.0.0.1', 'port': 8447}
2021-12-02T16:42:24.072 harvester harvester_server        : INFO     Cannot connect to host 127.0.0.1:8447 ssl:<ssl.SSLContext object at 0x000001ED0DAC6240> [The remote computer refused the network connection]
2021-12-02T16:42:24.510 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-12-02T16:42:24.513 wallet wallet_server              : DEBUG    Connecting: wss://127.0.0.1:8444/ws, Peer info: {'host': '127.0.0.1', 'port': 8444}

I don't understand what remote computer chia is trying to connect to. I thought 127.0.0.1 was the localhost, the PC that chie.exe is running on.
Very strange.

**Comment by nothingshocking** [comment]
I pulled 8771 earlier and then started the farmer (not just the node) from CLI (no GUI) to see how it went. It took over an hour to stop showing "reconnecting to peer, cannot connect to host 127.0.0.1". This is the sequence of log entries as it started connected. 

`2021-12-02T12:27:55.806 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0xffff81f506c0> [Connect call failed ('127.0.0.1', 8444)]
2021-12-02T12:27:56.166 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0xffff93f06f40> [Connect call failed ('127.0.0.1', 8444)]
2021-12-02T12:27:59.134 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-12-02T12:27:59.620 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-12-02T12:28:00.077 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0xffff78aa00c0> [Connect call failed ('127.0.0.1', 8444)]
2021-12-02T12:28:00.431 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0xffff9801c140> [Connect call failed ('127.0.0.1', 8444)]
2021-12-02T12:28:03.153 full_node chia.full_node.full_node: INFO     Migrating legacy peer database from *******/.chia/mainnet/db/peer_table_node.sqlite
2021-12-02T12:28:03.169 full_node full_node_server        : INFO     Started listening on port: 8444
2021-12-02T12:28:03.471 full_node full_node               : INFO     Started full_node service on network_id: mainnet
2021-12-02T12:28:03.487 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-12-02T12:28:03.713 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-12-02T12:28:06.243 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-12-02T12:28:06.286 farmer farmer_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-12-02T12:28:06.292 daemon chia.daemon.server         : INFO     Register service {'service': 'chia_full_node'}
2021-12-02T12:28:06.729 wallet chia.wallet.wallet_node    : INFO     Validated, fork point is 817165
2021-12-02T12:28:07.193 daemon chia.daemon.server         : INFO     registered for service chia_full_node
2021-12-02T12:28:07.509 wallet chia.wallet.wallet_node    : INFO     self.sync_event.set()
2021-12-02T12:28:07.757 daemon chia.daemon.server         : INFO     {'success': True}
2021-12-02T12:28:07.930 full_node chia.full_node.full_node: INFO     Starting to perform sync.
2021-12-02T12:28:08.660 full_node chia.full_node.full_node: INFO     Waiting to receive peaks from peers.
2021-12-02T12:28:20.455 wallet chia.full_node.weight_proof: INFO     validate weight proof peak height 1223588
2021-12-02T12:28:20.870 wallet chia.full_node.weight_proof: INFO     validating 3186 sub epochs
2021-12-02T12:28:22.708 full_node chia.full_node.full_node: INFO     Writing migrated peer data to ********/.chia/mainnet/db/peers.dat
2021-12-02T12:28:23.091 full_node chia.server.address_manager_store: INFO     Serializing peer data
2021-12-02T12:28:29.342 full_node chia.full_node.full_node: INFO     Collected a total of 3 peaks.
2021-12-02T12:28:29.666 full_node chia.full_node.full_node: INFO     Selected peak 1223634, 0bc987696467f7068355c8e6d02dd80880563b567115d6ff892fb30fa17c9745
2021-12-02T12:28:30.273 full_node chia.full_node.full_node: INFO     Total of 2 peers with peak 1223634
2021-12-02T12:28:30.716 full_node chia.full_node.full_node: INFO     Requesting weight proof from peer 36.161.224.174 up to height 1223634
2021-12-02T12:28:39.828 full_node chia.full_node.weight_proof: INFO     create weight proof peak 67a2ef24ccdf88aff50b52816fbc57a6b2e27e1e4d8c3d6492368de195e73d7f 1223128
2021-12-02T12:28:41.040 full_node chia.server.address_manager_store: INFO     Loading peers from ********/.chia/mainnet/db/peers.dat
`

**Comment by keliew** [comment]
@nothingshocking try just starting the `node` only.

**Comment by emlowe** [comment]
It will be slow the first time. The idea is the next start should be faster though.

**Comment by nothingshocking** [comment]
> @nothingshocking try just starting the `node` only.

I'll try that but I need the the wallet to finish sync'ing. If I start only the node that doesn't support my farm and separate harvester, does it?

**Comment by keliew** [comment]
> > @nothingshocking try just starting the `node` only.
> 
> I'll try that but I need the the wallet to finish sync'ing. If I start only the node that doesn't support my farm and separate harvester, does it?

Yes, that's right. Once your `node` starts up OK, you can start the other services separately. I'd start the `harvester` first, then `farmer`, then `wallet`. See `chia start -h` for more info.

I'm not exactly sure on the technicality of the works, but depending on the hardware configuration, starting up slowly through manual intervention can make a significant difference.

**Comment by nothingshocking** [comment]
After that first restart, subsequent starts have been remarkably different starting up in a few minutes or less instead of 45+. This has been a big help. I am still working through how best to start up but the new changes are working well for me.

**Comment by William10025** [comment]
I've been having the same issue for weeks. Chia runs fine for several hours, sometimes a day or two and then it crashes.  I'm running 1.2.11 CLI and the only way I can get Chia to work is to reboot since 'chia stop all -d' doesn't work.

```
2021-12-31T10:33:38.753 harvester chia.harvester.harvester: INFO     refresh_batch: event batch_processed, loaded 0, removed 0, processed 211, remaining 0, duration: 0.03 seconds
2021-12-31T10:33:38.754 harvester chia.harvester.harvester: INFO     refresh_batch: event done, loaded 0, removed 0, processed 211, remaining 0, duration: 0.03 seconds
2021-12-31T10:33:41.993 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-12-31T10:33:42.998 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-12-31T10:34:15.993 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-12-31T10:34:16.999 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}

```
Is the solution to pull a new build or to not use "chia start all' and instead start the node first, followed by the harvester, then farmer, then wallet?

Thanks!

**Comment by keliew** [comment]
> Is the solution to pull a new build or to not use "chia start all' and instead start the node first, followed by the harvester, then farmer, then wallet?

You shouldn't be running `chia start all`. Usually, at most, `chia start farmer`.

**Comment by Bosswell** [comment]
The only solution I found is to downgrade the client to version 1.2.7. Seems to be working.

```
chia stop all -d

git pull
git checkout 1.2.7
sh install.sh

. ./activate
chia start farmer

```

**Comment by dadatuputi** [comment]
> The only solution I found is to downgrade the client to version 1.2.7. Seems to be working.
> 
> ```
> chia stop all -d
> 
> git pull
> git checkout 1.2.7
> sh install.sh
> 
> . ./activate
> chia start farmer
> ```

Chiming in that this is also the only thing that got me going.

**Comment by Bosswell** [comment]
If anyone is still struggling with this problem, upgrade your version to 1.3.2. This problem is fixed.

**Comment by vc5** [comment]
chia_version:1.3.4
run`grep ~/.chia/mainnet/log/debug.log -e chia.full_node`,get
```
2022-04-08T08:08:36.842 full_node chia.full_node.full_node: INFO     opening blockchain DB: synchronous=FULL
2022-04-08T08:08:36.846 full_node chia.full_node.full_node: INFO     Initializing blockchain from disk
2022-04-08T08:08:36.847 full_node chia.full_node.full_node: INFO     Selected multiprocessing start method: default
2022-04-08T08:09:16.049 wallet chia.full_node.weight_proof: INFO     validating 4703 sub epochs
2022-04-08T08:14:41.415 wallet chia.full_node.weight_proof: INFO     validating 4703 sub epochs
2022-04-08T08:22:09.206 wallet chia.full_node.weight_proof: INFO     validating 4703 sub epochs
2022-04-08T08:23:30.113 wallet chia.full_node.weight_proof: INFO     validating 4703 sub epochs
```

then I waited 4 hours,it still show `Cannot connect to host 127.0.0.1:8444 ssl`
so I type 
```bash
root@Tower:/chia-blockchain# ps -aux |grep full_node
root      3182  0.4  0.7 299596 116048 ?       Sl   08:08   0:52 chia_full_node
```
It seems that chia_full_node process state is sleep

**Comment by pika28** [comment]
Hello,

I've been having the same problem for a few days. I updated to version 1.4.0. This does not correct the problem.

```
Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x00000201639BCAC0> [Remote system refused network connection]
Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x00000256E5039CC0> [Remote system refused network connection]
```

I don't understand.

I use google translate to exchange with you.

**Comment by HVNC1** [comment]
1.4.0 проблема такая же вы будете ее решать?

**Comment by Baatezu** [comment]
2022-08-20T23:14:30.210 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f173c19cbc0> [Connect call failed ('127.0.0.1', 8444)]
2022-08-20T23:14:33.211 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
