### ISSUE TITLE
Wallet does not sync [BUG]

### ISSUE THREAD

**Issue by GBourb** [Chia-Network/chia-blockchain#846]
*Hello everyone,

Good news is... My node is synced (it's great)

But my wallet is not. 

My node is at  Peak : 58663 (02/06/2021 14:37:10)

My wallet is at : 54546 

Status : not synced - Connections : 1 

On windows 10

Thanks

**Comment by mariano54** [comment]
Fixed in beta 27

**Comment by dorkmo** [comment]
my wallet is up to date to the current height, but its still showing not synced for status. thanks

**Comment by erock24601** [comment]
Also having the same issue windows 10 beta 27

**Comment by staviq** [comment]
Same problem here, i started on beta27 no upgrades

Node synced but wallet is not.

**Comment by dorkmo** [comment]
@staviq does the height on the wallet match the node height? or is the wallet behind?

**Comment by staviq** [comment]
> 
> 
> @staviq does the height on the wallet match the node height? or is the wallet behind?

in the gui, main tab says:

Peak height 42951

on the wallet tab it says

height: 42951

**Comment by daquinons** [comment]
Same, node synced, wallet not synced and both have same height. Latest RC.

**Comment by hoffmang9** [comment]
The 'wallet erroneously says it's not synced' issue is still present so re-opening.

**Comment by hoffmang9** [comment]
@mariano54 is there a more on point issue where the wallet is synced but it's just saying it is not incorreclty?

**Comment by mariano54** [comment]
I don't know if there's another issue on github for this. However, I think I fixed this in the recent merge: ms.rpcs branch.

**Comment by wheatrick** [comment]
this MAY be a related question or maybe i need to rtfm a little better.  (first post)

all was going well and i even farmed two blocks (huzzah) then my wallet wouldn't synch.  i restarted the app, my computer, etc.  no joy.  then i noticed there was a new release so i downloaded 0.2.2.exe windows 10

with that i went from 27 to rc2 and was asked to drag n drop my wallet backup but i have no idea how to backup the wallet contained in the ~27 folder.  any advice?  cuz without this step, i appear to be back to zero contents in wallet ;-(

**Comment by ayaseen** [comment]
Restarting the whole process makes the plot disappear!!

**Comment by hoffmang9** [comment]
Wallet sync is fixed in RC4 - can still erroneously say you're not synced when the block heights are the same in node and wallet though.
